"""Remove project_id from rfps table

Revision ID: 244a0f6c212d
Revises: 001
Create Date: 2025-06-07 23:09:53.449862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '244a0f6c212d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_user_association', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('project_user_association', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_rfps_id'), 'rfps', ['id'], unique=False)
    op.drop_constraint('rfps_project_id_fkey', 'rfps', type_='foreignkey')
    op.drop_column('rfps', 'project_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('rfps', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rfps_project_id_fkey', 'rfps', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_rfps_id'), table_name='rfps')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('project_user_association', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('project_user_association', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ### 