"""Fix UserRole enum serialization

Revision ID: 6ced8644e8db
Revises: 244a0f6c212d
Create Date: 2025-06-07 23:31:32.390799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ced8644e8db'
down_revision = '244a0f6c212d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 